package Form;

import database.KetNoi;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

public class DangKyKhachMoi extends javax.swing.JFrame {
    public DangKyKhachMoi() {
        initComponents();
        setTitle("Đăng kí khách mới");
        
    }
    String manv;
    public void setmanv(String a){
        manv = a;
    }String maql;
    public void setmaql(String a){
        maql = a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTKH = new javax.swing.JTextField();
        txtMKH = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        Makh = new javax.swing.JLabel();
        lbDiachi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiachi1 = new javax.swing.JLabel();
        txtTenkh = new javax.swing.JLabel();
        txtDC = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        cbGioitinh = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnThem_KH = new javax.swing.JButton();
        btnThoat_KH1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setLocation(new java.awt.Point(200, 200));
        setMinimumSize(null);
        setName("DKKM"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(784, 463));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        txtTKH.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtMKH.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtMKH.setText("Tự động");
        txtMKH.setEnabled(false);
        txtMKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKHActionPerformed(evt);
            }
        });

        txtCMND.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        Makh.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Makh.setText("Mã khách hàng");

        lbDiachi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbDiachi.setText("Địa chỉ");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("CMND");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Số điện thoại");

        txtDiachi1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtDiachi1.setText("Giới tính");

        txtTenkh.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtTenkh.setText("Tên khách hàng");

        txtDC.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        cbGioitinh.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cbGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Makh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDiachi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDiachi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addComponent(txtTenkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDC)
                    .addComponent(txtTKH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCMND)
                    .addComponent(txtMKH)
                    .addComponent(cbGioitinh, 0, 147, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Makh))
                    .addComponent(txtMKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtTenkh))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachi1)
                    .addComponent(cbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbDiachi))
                    .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        btnThem_KH.setBackground(new java.awt.Color(0, 153, 153));
        btnThem_KH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnThem_KH.setText("Thêm");
        btnThem_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_KHActionPerformed(evt);
            }
        });

        btnThoat_KH1.setBackground(new java.awt.Color(0, 153, 153));
        btnThoat_KH1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnThoat_KH1.setText("Đóng");
        btnThoat_KH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat_KH1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat_KH1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(btnThem_KH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnThem_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnThoat_KH1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("ĐĂNG KÝ KHÁCH MỚI");
        jLabel1.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(250, 250, 250))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThem_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_KHActionPerformed
        String tenkh = txtTKH.getText();
        String diachi = txtDC.getText();
        String gioitinh = cbGioitinh.getSelectedItem().toString();
        String sdt = txtSDT.getText();
        String cmnd = txtCMND.getText();

        // Kiểm tra đầu vào của các trường JTextField
        if (tenkh.trim().isEmpty() || diachi.trim().isEmpty() || sdt.trim().isEmpty() || cmnd.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        Connection kn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            kn = (Connection) KetNoi.ketNoi();

            // Kiểm tra xem CMND đã tồn tại trong hệ thống chưa
            String sqlCheckCMND = "SELECT COUNT(*) FROM khachhang WHERE cmnd = ?";
            pst = kn.prepareStatement(sqlCheckCMND);
            pst.setString(1, cmnd.trim());
            rs = pst.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "Khách hàng đã có trong hệ thống!");
                return;
            }

            // Truy vấn mã khách hàng lớn nhất hiện tại
            String sqlMaxMakh = "SELECT MAX(makh) AS max_makh FROM khachhang";
            pst = kn.prepareStatement(sqlMaxMakh);
            rs = pst.executeQuery();
            String newMakh;
            if (rs.next()) {
                String maxMakh = rs.getString("max_makh");
                if (maxMakh != null) {
                    // Tăng mã khách hàng lên 1
                    int newMakhInt = Integer.parseInt(maxMakh.substring(2)) + 1;
                    newMakh = "KH" + String.format("%06d", newMakhInt);
                } else {
                    // Trường hợp bảng rỗng, bắt đầu với mã KH000001
                    newMakh = "KH000001";
                }
            } else {
                // Trường hợp bảng rỗng, bắt đầu với mã KH000001
                newMakh = "KH000001";
            }

            // Thực hiện truy vấn thêm khách hàng mới
            String sqlInsert = "INSERT INTO khachhang (makh, tenkh, gioitinh, diachi, sdt, cmnd) VALUES (?, ?, ?, ?, ?, ?)";
            pst = kn.prepareStatement(sqlInsert);
            pst.setString(1, newMakh);
            pst.setString(2, tenkh.trim());
            pst.setString(3, gioitinh);
            pst.setString(4, diachi.trim());
            pst.setString(5, sdt.trim());
            pst.setString(6, cmnd.trim());
            pst.executeUpdate();

            // Thông báo thành công
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (kn != null) kn.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThem_KHActionPerformed

    private void btnThoat_KH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat_KH1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoat_KH1ActionPerformed

    private void txtMKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKHActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ThuePhong tp = new ThuePhong();
        tp.loadALL();
        if(manv == null){
            tp.setMaQL(maql);
        }else{
            tp.setmanv(manv);
        }
        tp.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyKhachMoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Makh;
    private javax.swing.JButton btnThem_KH;
    private javax.swing.JButton btnThoat_KH1;
    private javax.swing.JComboBox<String> cbGioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbDiachi;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDC;
    private javax.swing.JLabel txtDiachi1;
    private javax.swing.JTextField txtMKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTKH;
    private javax.swing.JLabel txtTenkh;
    // End of variables declaration//GEN-END:variables
}
